<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Fixedtablerate.aspx.cs" Inherits="WEB.Fixedtablerate" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            text-align: center;
        }
        .auto-style2 {
            margin-right: 14px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div class="auto-style1">
    
        <strong>Fixed Rate Table<br />
        <br />
        Here you can view the previous records and edit them as well</strong></div>
        <asp:Panel ID="Panel1" runat="server" Height="719px">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="ID" DataSourceID="SqlDataSource1" EmptyDataText="There are no data records to display." AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" Height="533px" Width="1151px" CssClass="auto-style2">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <Columns>
                    <asp:BoundField DataField="ID" HeaderText="ID" ReadOnly="True" SortExpression="ID" InsertVisible="False" />
                    <asp:BoundField DataField="OfficeNames" HeaderText="OfficeNames" SortExpression="OfficeNames" />
                    <asp:BoundField DataField="location" HeaderText="location" SortExpression="location" />
                    <asp:BoundField DataField="Vehicle" HeaderText="Vehicle" SortExpression="Vehicle" />
                    <asp:BoundField DataField="Source" HeaderText="Source" SortExpression="Source" />
                    <asp:BoundField DataField="Destination" HeaderText="Destination" SortExpression="Destination" />
                    <asp:BoundField DataField="Fare" HeaderText="Fare" SortExpression="Fare" />
                    <asp:BoundField DataField="Account" HeaderText="Account" SortExpression="Account" />
                </Columns>
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:BuzybeezWebConnectionString %>" DeleteCommand="DELETE FROM [Fixedfare] WHERE [ID] = @ID" InsertCommand="INSERT INTO [Fixedfare] ([OfficeNames], [location], [Vehicle], [Source], [Destination], [Fare], [Account]) VALUES (@OfficeNames, @location, @Vehicle, @Source, @Destination, @Fare, @Account)" SelectCommand="SELECT [ID], [OfficeNames], [location], [Vehicle], [Source], [Destination], [Fare], [Account] FROM [Fixedfare]" UpdateCommand="UPDATE [Fixedfare] SET [OfficeNames] = @OfficeNames, [location] = @location, [Vehicle] = @Vehicle, [Source] = @Source, [Destination] = @Destination, [Fare] = @Fare, [Account] = @Account WHERE [ID] = @ID">
                <DeleteParameters>
                    <asp:Parameter Name="ID" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="OfficeNames" Type="String" />
                    <asp:Parameter Name="location" Type="String" />
                    <asp:Parameter Name="Vehicle" Type="String" />
                    <asp:Parameter Name="Source" Type="String" />
                    <asp:Parameter Name="Destination" Type="String" />
                    <asp:Parameter Name="Fare" Type="Double" />
                    <asp:Parameter Name="Account" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="OfficeNames" Type="String" />
                    <asp:Parameter Name="location" Type="String" />
                    <asp:Parameter Name="Vehicle" Type="String" />
                    <asp:Parameter Name="Source" Type="String" />
                    <asp:Parameter Name="Destination" Type="String" />
                    <asp:Parameter Name="Fare" Type="Double" />
                    <asp:Parameter Name="Account" Type="String" />
                    <asp:Parameter Name="ID" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>

            <a href="Fixedrate.aspx"> Back to Fixedrate</a>
        </asp:Panel>
    </form>
</body>
</html>
